export const actionTypes = {
  ADD_POST: "ADD-POST",
  UPDATE_NEW_POST_TEXT: "UPDATE-NEW-POST-TEXT",
  ADD_MESSAGE: "ADD-MESSAGE",
  UPDATE_NEW_MESSAGE_TEXT: "UPDATE-NEW-MESSAGE-TEXT",
  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  SET_USERS: "SET-USERS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_TOTAL_USER_COUNT: "SET_TOTAL_USER_COUNT",
};
